### PR TITLE
feat: usage of ESLint v8

### LINKED ISSUE #273: Parsing error for static class variables
**What version of this package are you using?**
16.0.1 Latest

**What operating system, Node.js, and npm version?**
Windows, node v16.13.1, npm v8.1.2

**What happened?**
Semistandard considers static variables on a class as : "Parsing error: Unexpected token =" 
parseError

**What did you expect to happen?**
In standard there is no Parse error. ES6 should allow static variables on classes.
noError

I can't disable this error with /* eslint-disable */

**Are you willing to submit a pull request to fix this bug?**
Not sure where to look to figure out how/why this is different.

### PR DESCRIPTION
**Pull request by voxpelli**
Work in progress on upgrading this module to use the new [`eslint-config-semistandard@17.0.0`](https://github.com/standard/eslint-config-semistandard/releases/tag/v17.0.0)

See https://github.com/standard/eslint-config-standard/issues/229

Fixes #273

### CODE REVIEW

**Comment by voxpelli** [comment]
@Divlo I wanted to look into eg. the external tests + I was considering whether to wait for the `old-test` PR in `standard` and copy that one in here as well

**Comment by markwylde** [comment]
Any update on this? Can we get this merged?

**Comment by nordluf** [comment]
Since I am not the only one who wants to use this updated version, I have published an npmjs version: https://www.npmjs.com/package/@umpacken/semistandard

If you want to do a seamless update, you can use an npm alias in your package.json like this:

```
-    "semistandard": "^16.0.1",
+    "semistandard": "npm:@umpacken/semistandard@^16.1.0",
```

**Comment by wesleytodd** [comment]
Hello my fine folks! I just pulled this branch and ran the tests as well as ran it against a project of mine which uses class private fields (the feature I want) and all seems to work well. I am happy to do what it takes to get help get this across the finish line if someone will but help me know what to do.

A lot has changed, but I used to help maintain `happiness` which was another similar extension of `standard`, so if this particular fork (which my team is using a bit) needs help I am happy to if I can. Just taking a guess since this PR has been hanging for a while now that that might be the case (not complaining, I know how this stuff goes).

**Comment by wesleytodd** [comment]
Hey @Divlo, I noticed Pelle remove themselves so I am thinking maybe you are the right person to help. If this project is having resourcing troubles I am happy to help. If nothing else, we could just automate pulling in the latest `standard` updates and opening PRs like this so all that is necessary is to spot check it and merge to release.  Let me know if you or someone else can help me onboard here so I can help.

**Comment by Divlo** [comment]
Hey! @wesleytodd 
Thanks for reaching out!

I think the PR is ready to land as is.
@voxpelli Could you explain, what is the state of the PR, please? What can be done?
However I can't release new version on npm anyway.

There is a similar issue of long standing PR (even merged) but not released in `standard-engine`.

The `standard` organization suffers from not enough active maintainers with ability to push new releases on npm.
Not sure what to do about it.

**Comment by voxpelli** [comment]
@Divlo I sadly can't remember and sadly have no time to spend on Standard. I do agree that there are not enough active maintainers here.

**Comment by wesleytodd** [comment]
> Could you explain, what is the state of the PR, please? What can be done?

I tested it out and it worked without issue. Are there other checks you would usually do before releasing? I am happy to do them.

> However I can't release new version on npm anyway.
> The standard organization suffers from not enough active maintainers with ability to push new releases on npm.

Who has publish on these? I wonder if we could add [Release Please](https://github.com/googleapis/release-please) and then have whoever has the publish can add the tokens to the repos.  Who is it that has publish rights on these two packages?

---

I can't promise much time, but I have been a big fan of this approach to linting for a long time and really appreciate the work y'all have done to keep it going. If the project is suffering I can both keep an eye out for folks looking to contribute and point them here as well as give a little time/effort to helping automate parts like the merge and release flow so it is less hard to maintain the "forks" of `standard`.

**Comment by Divlo** [comment]
@wesleytodd We can definitely automate the release process. There is a similar issue open in `ts-standard`: https://github.com/standard/ts-standard/issues/266.

I'm not familiar with Release Please, but I think [semantic-release](https://www.npmjs.com/package/semantic-release) can be a good fit too, similarly to https://github.com/standard/eslint-config-standard-with-typescript/issues/840.

Would be greatly appreciated if any one want to open a PR to setup the GitHub Actions to automate that. :+1:
Maybe then someone with the rights on both the GitHub repo and npm can then set the tokens, so we can publish automatically. @standard/team 

Meanwhile, we will merge this PR, it is ready. :rocket:

**Comment by wesleytodd** [comment]
> I'm not familiar with Release Please, but I think [semantic-release](https://www.npmjs.com/package/semantic-release) can be a good fit too

My main reason for going with release please is I trust it's author (Benjamin Coe, node.js core contributor and prolific module author) and it is well supported.  For a while I was working with Ben and a few others on stuff related to conventional commits and it was while he was working on Release Please.

I am happy to go whichever route folks already working in this project want, just sharing why I like Release Please :)

> Would be greatly appreciated if any one want to open a PR to setup the GitHub Actions to automate that.

Yep, that is exactly why I think this kind of automation would be good. The publish token is still restricted, but "publish rights" are given to anyone with write access on the repo.

**Comment by wesleytodd** [comment]
A bit of "how the sausage is made" on these:

1. [Release Please uses the new CC parser package](https://github.com/googleapis/release-please/blob/main/package.json#L70) which is much better than old stuff
2. [semantic-release](https://github.com/semantic-release/commit-analyzer/blob/master/package.json#L19-L21) is still on the older stuff.

Not really a good reason to make a decision, but we were working on a v2 for Conventional Commits with the intent to better support monorepos and all the other stuff the original didn't really take into account. If folks ever have time to pick that work back up I think it will likely be where new supported features land first.

**Comment by wesleytodd** [comment]
@voxpelli I see you have publish rights. Would you mind adding @Divlo or passing the responsibility to someone else on the list who has published? I see a few others on there but didn't want to ping them in unless you were unable to help.

**Comment by voxpelli** [comment]
@wesleytodd Sorry, maybe @feross, @LinusU, @Flet or someone else knows

**Comment by wesleytodd** [comment]
Thanks! I didn't want to bother you further, just wasn't sure who to ping who had publish rights.

**Comment by voxpelli** [comment]
Since I did another release in the standard org I threw this in as well, `17.0.0` released

**Pull request merged**
